# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_guid', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_guid', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManager.Client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('value', models.FloatField()),
                ('order_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManager.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_guid', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManager.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManager.Recipe'),
        ),
    ]
